# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Extinction Rebellion Cambridge
email: info@xrcambridge.org
description: >- # this means to ignore newlines until "baseurl:"
  Join the people's rebellion to save life on earth
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://xrcambridge.org' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xr_cambridge

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-redirect-from
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

webmaster_verifications:
  google: 'Bzg3CtmzEFlA0QrhqirrVwqbKugvqZWTLYB8l5ASru4'
  bing: 'EE097CDF86EB65D3183A2F65EA43B9E7'

facebook:
  publisher: 'https://en-gb.facebook.com/xrcambridge/'
  publisher_id: '1600553066711419'
  app_id: '644189972724811'

twitter:
  username: xr_cambridge
  card: summary_large_image

tag_archive:
  path: /tags/

category_archive:
  path: /categories/

og_image: /assets/images/preview.jpg

social:
  type: 'Organization'
  name: 'Extinction Rebellion Cambridge'
  links:
    - 'https://twitter.com/xr_cambridge'
    - 'https://facebook.com/xrcambridge/'
    - 'https://www.instagram.com/xrcambridge/'

defaults:
  # _posts
  - scope:
      path: ''
    values:
      image: '/assets/images/generic-social-media-share.png'
      lang: 'en_GB'
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

footer:
  links:
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/xr_cambridge'
      target: '_blank'
    - label: 'Facebook'
      icon: 'fab fa-fw fa-facebook-square'
      url: 'https://en-gb.facebook.com/xrcambridge/'
      target: '_blank'
    - label: 'Instagram'
      icon: 'fab fa-fw fa-instagram'
      url: 'https://www.instagram.com/xrcambridge/'
      target: '_blank'
    - label: 'Donate'
      icon: 'fas fa-donate'
      url: '/donate'
      target: ''

jekyll-minifier:
  compress_css: false
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - newsletter-preview.html
  - facebook_pages.json
  - .browserslistrc
  - postcss.config.js
  - gruntfile.js
  - .bin/
  - .jekyll-cache
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - cypress/
  - results/

# Build settings
include:
  - '_pages'
#  - '/node_modules/@xrmcr-digital/search/dist/search.umd.min.js'
